<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fiscal.Api\Fiscal.Api.csproj" />
    <ProjectReference Include="..\..\src\Fiscal.Domain\Fiscal.Domain.csproj" />
    <ProjectReference Include="..\..\src\Fiscal.Application\Fiscal.Application.csproj" />
    <ProjectReference Include="..\..\src\Fiscal.Infrastructure\Fiscal.Infrastructure.csproj" />
  </ItemGroup>

</Project>
