// <auto-generated />
using System;
using Fiscal.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fiscal.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(FiscalDbContext))]
    [Migration("20260905033029_LotesEOutbox")]
    partial class LotesEOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fiscal.Domain.Documentos.DocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<string>("CnpjEmitente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTimeOffset>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentoDestinatario")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NomeDestinatario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeEmitente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UfEmitente")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UfEmitente")
                        .HasDatabaseName("ix_documento_fiscal_uf");

                    b.HasIndex("CnpjEmitente", "DataEmissao")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_documento_fiscal_cnpj_data");

                    b.HasIndex("DocumentoDestinatario", "DataEmissao")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_documento_fiscal_destinatario_data");

                    b.HasIndex("Tipo", "ChaveAcesso")
                        .IsUnique()
                        .HasDatabaseName("ux_documento_fiscal_tipo_chave");

                    b.ToTable("documento_fiscal", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Documentos.ItemDocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cfop")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ncm")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_documento_fiscal_item_documento");

                    b.ToTable("documento_fiscal_item", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Lotes.ItemDoLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChaveDeArmazenamento")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTimeOffset?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<int>("TamanhoEmBytes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_lote_ingestao_item_lote");

                    b.ToTable("lote_ingestao_item", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Lotes.LoteDeIngestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CnpjProprietario")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CnpjProprietario", "RecebidoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_lote_ingestao_cnpj_recebido");

                    b.ToTable("lote_ingestao", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Processamento.EventoPendente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MensagemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_evento_pendente_nao_publicado")
                        .HasFilter("\"PublicadoEm\" IS NULL");

                    b.ToTable("evento_pendente", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Processamento.MensagemProcessada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Consumidor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MensagemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ProcessadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MensagemId", "Consumidor")
                        .IsUnique()
                        .HasDatabaseName("ux_mensagem_processada");

                    b.ToTable("mensagem_processada", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Resumos.ResumoEmitente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CnpjEmitente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("QuantidadeDocumentos")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CnpjEmitente", "Competencia")
                        .IsUnique()
                        .HasDatabaseName("ux_resumo_emitente_cnpj_competencia");

                    b.ToTable("resumo_emitente", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Documentos.ItemDocumentoFiscal", b =>
                {
                    b.HasOne("Fiscal.Domain.Documentos.DocumentoFiscal", null)
                        .WithMany("Itens")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fiscal.Domain.Lotes.ItemDoLote", b =>
                {
                    b.HasOne("Fiscal.Domain.Lotes.LoteDeIngestao", null)
                        .WithMany("Itens")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fiscal.Domain.Documentos.DocumentoFiscal", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Fiscal.Domain.Lotes.LoteDeIngestao", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
